# Generated by Apache BigTop Manager.
# Generated datetime is ${.now}.
<#compress>
    <#list model as key,value>
        <#if value??>
            <#if value?string == 'true'>
                export ${key}=true
            <#elseif value?string == 'false'>
                export ${key}=false
            <#else>
                export ${key}=${value}
            </#if>
        </#if>
    </#list>
</#compress>