<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
<!-- Generated by Apache BigTop Manager. -->
<!-- Generated datetime is ${.now?datetime}. -->
<configuration>
    <#list model as key,value>
        <#if value??>
    <property>
        <name>${key}</name>
        <#if value?string == 'true'>
        <value>true</value>
        <#elseif value?string == 'false'>
        <value>false</value>
        <#else>
        <value>${value}</value>
        </#if>
    </property>
        </#if>
    </#list>
</configuration>