{
 "title": "Cluster",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "${cluster_label}", "label": "Cluster", "query": "label_values(${cluster_label})" },
   { "name": "resolution", "label": "Resolution", "query": "1s, 5s, 1m, 3m, 5m" }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Global CPU  Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  agent_host_monitoring_cpu{cpuUsage=\"cpuUsage\", ${cluster_label}<#noparse>=~\"${cluster}\"</#noparse>}\n) / count(\n  count by (instance) (\n    agent_host_monitoring_cpu{cpuUsage=\"cpuUsage\", ${cluster_label}<#noparse>=~\"${cluster}\"</#noparse>}\n  )\n)",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Cluster CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  agent_host_monitoring_cpu{cpuUsage=\"cpuUsage\", ${cluster_label}<#noparse>=~\"${cluster}\"</#noparse>}\n) / count(\n  count by (instance) (\n    agent_host_monitoring_cpu{cpuUsage=\"cpuUsage\", ${cluster_label}<#noparse>=~\"${cluster}\"</#noparse>}\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU LoadAvg",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  agent_host_monitoring_cpu{cpuUsage=\"cpuLoadAvgMin_1\", ${cluster_label}<#noparse>=~\"${cluster}\"</#noparse>}\n) / count(\n  count by (instance) (\n    agent_host_monitoring_cpu{cpuUsage=\"cpuLoadAvgMin_1\", ${cluster_label}<#noparse>=~\"${cluster}\"</#noparse>}\n  )\n)",
     "legendFormat": "Min_1"
    },
    {
     "expr": "sum(\n  agent_host_monitoring_cpu{cpuUsage=\"cpuLoadAvgMin_5\", ${cluster_label}<#noparse>=~\"${cluster}\"</#noparse>}\n) / count(\n  count by (instance) (\n    agent_host_monitoring_cpu{cpuUsage=\"cpuLoadAvgMin_5\", ${cluster_label}<#noparse>=~\"${cluster}\"</#noparse>}\n  )\n)",
     "legendFormat": "Min_5"
    },
    {
     "expr": "sum(\n  agent_host_monitoring_cpu{cpuUsage=\"cpuLoadAvgMin_15\", ${cluster_label}<#noparse>=~\"${cluster}\"</#noparse>}\n) / count(\n  count by (instance) (\n    agent_host_monitoring_cpu{cpuUsage=\"cpuLoadAvgMin_15\", ${cluster_label}<#noparse>=~\"${cluster}\"</#noparse>}\n  )\n)",
     "legendFormat": "Min_15"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Global RAM Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(\n  agent_host_monitoring_mem{memUsage=\"memIdle\", ${cluster_label}<#noparse>=~\"${cluster}\"</#noparse>}\n) / sum(\n  agent_host_monitoring_mem{memUsage=\"memTotal\", ${cluster_label}<#noparse>=~\"${cluster}\"</#noparse>}\n)) /\ncount(\n  count by (instance) (\n    agent_host_monitoring_mem{memUsage=\"memTotal\", ${cluster_label}<#noparse>=~\"${cluster}\"</#noparse>}\n  )\n)",
     "legendFormat": "Real"
    }
   ]
  },
  {
   "title": "Cluster Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(\n  agent_host_monitoring_mem{memUsage=\"memIdle\", ${cluster_label}<#noparse>=~\"${cluster}\"</#noparse>}\n) / sum(\n  agent_host_monitoring_mem{memUsage=\"memTotal\", ${cluster_label}<#noparse>=~\"${cluster}\"</#noparse>}\n)) /\ncount(\n  count by (instance) (\n    agent_host_monitoring_mem{memUsage=\"memTotal\", ${cluster_label}<#noparse>=~\"${cluster}\"</#noparse>}\n  )\n)",
     "legendFormat": "Memory usage in %"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(\n  agent_host_monitoring_mem{memUsage=\"memIdle\", ${cluster_label}<#noparse>=~\"${cluster}\"</#noparse>}\n) / sum(\n  agent_host_monitoring_mem{memUsage=\"memTotal\", ${cluster_label}<#noparse>=~\"${cluster}\"</#noparse>}\n)) /\ncount(\n  count by (instance) (\n    agent_host_monitoring_mem{memUsage=\"memTotal\", ${cluster_label}<#noparse>=~\"${cluster}\"</#noparse>}\n  )\n)",
     "legendFormat": "Real"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Persistent Volumes - Usage in %",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(\n  agent_host_monitoring_disk{diskUsage=\"diskFreeSpace\", ${cluster_label}<#noparse>=~\"${cluster}\"</#noparse>}\n) / sum(\n  agent_host_monitoring_disk{diskUsage=\"diskTotalSpace\", ${cluster_label}<#noparse>=~\"${cluster}\"</#noparse>}\n)) /\ncount(\n  count by (instance) (\n    agent_host_monitoring_disk{diskUsage=\"diskFreeSpace\", ${cluster_label}<#noparse>=~\"${cluster}\"</#noparse>}\n  )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Persistent Volumes - Usage in %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(\n  agent_host_monitoring_disk{diskUsage=\"diskFreeSpace\", ${cluster_label}<#noparse>=~\"${cluster}\"</#noparse>}\n) / sum(\n  agent_host_monitoring_disk{diskUsage=\"diskTotalSpace\", ${cluster_label}<#noparse>=~\"${cluster}\"</#noparse>}\n)) /\ncount(\n  count by (instance) (\n    agent_host_monitoring_disk{diskUsage=\"diskFreeSpace\", ${cluster_label}<#noparse>=~\"${cluster}\"</#noparse>}\n  )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}