#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

bigtop:
  manager:
    grpc:
      port: 8835

spring:
  banner:
    charset: utf-8
  application:
    name: bigtop-manager-agent
  main:
    banner-mode: log

grpc:
  server:
    port: ${bigtop.manager.grpc.port}

server:
  port: 8081

logging:
  level:
    org:
      springframework:
        web:
          socket: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  metrics:
    enable:
      jvm: false
      logback: false
      executor: false
      process: false
      tomcat: false
      http: false
      system: false
      disk: false
      application: false
